theme: jekyll-theme-slate
title: Open Loganalyzer
description: This project wants to build a library to analyze log files based on custom regex entries. In a later stage, I'm planning to add a wpf application ready to use for windows users.
